spring:
  main:
    banner-mode: off
  application:
    name: ${project.artifactId}
camel:
  springboot:
    name: ${project.artifactId}
    use-mdc-logging: true
  rest:
    port: 9000
    context-path: /api
management:
  endpoint:
    camelroutes:
      enabled: true
      read-only: true
    health:
      enabled: true
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,camelroutes
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true