name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    # skip releases
    if: startsWith(github.ref, '[maven-release-plugin] prepare release') != true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          # needed for license-plugin to check last modified date of each file
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Override/recreate settings.xml
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          servers: '[{ "id": "github-arch-snapshots", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}" },{ "id": "github-plugins", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}" }]'
          plugin_repositories: '[{ "id": "github-plugins", "url": "https://maven.pkg.github.com/ms3inc/camel-restdsl-openapi-plugin" }]'
      - name: mvn clean verify
        run: ./mvnw -V --no-transfer-progress --batch-mode clean verify
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [ build ]
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: mvn clean deploy
        env:
          REPO_USER: ${{ secrets.REPO_USER }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
        run: "./mvnw -V --no-transfer-progress --batch-mode --settings .settings.xml clean \
        -Dlicense.skip=true -DskipTests -Darchetype.test.skip=true -Dmaven.install.skip=true deploy"