name: Publish package to GitHub Packages
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Start OTEL collector
        run: |
          docker run -d -p 127.0.0.1:4317:4317 --name collector otel/opentelemetry-collector:0.98.0
      - name: Override/recreate settings.xml
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          servers: '[{ "id": "github-arch-snapshots", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}" },{ "id": "github-snapshots", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}"},{ "id": "github-plugins", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}" }]'
          plugin_repositories: '[{ "id": "github-plugins", "url": "https://maven.pkg.github.com/ms3inc/camel-restdsl-openapi-plugin" }]'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GH_USERNAME: "${{ github.actor }}"
          GH_PAT: "${{ secrets.GITHUB_TOKEN }}"
      - name: Stop OTEL collector
        run: |
          docker stop collector
          docker rm collector