name: Publish package to GitHub Packages
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Override/recreate settings.xml
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          servers: '[{ "id": "github-arch-snapshots", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}" },{ "id": "github-snapshots", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}" }]'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GH_USERNAME: "${{ github.actor }}"
          GH_PAT: "${{ secrets.GITHUB_TOKEN }}"