name: release
on:
  workflow_dispatch:
    inputs:
      release_ver:
        description: 'Version to use when releasing'
        required: false
      snapshot_ver:
        description: 'Version to use for next development iteration'
        required: false
jobs:
  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: setup git
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
      - name: mvn clean release:prepare
        run: "./mvnw -V --no-transfer-progress --batch-mode --settings .settings.xml clean \
          -DreleaseVersion='${{ github.event.inputs.release_ver }}' \
          -DdevelopmentVersion='${{ github.event.inputs.snapshot_ver }}' \
          release:prepare"
      - name: mvn release:perform
        env:
          REPO_USER: ${{ secrets.REPO_USER }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
        run: "./mvnw -V --no-transfer-progress --batch-mode --settings .settings.xml \
          -Darguments='--settings .settings.xml -Dlicense.skip=true -DskipTests -Dmaven.install.skip=true' \
          release:perform"
